### ISSUE TITLE
`total-locked` endpoint issues bring whole website down

### ISSUE THREAD

**Issue by drptbl** [Synthetixio/synthetix-website#39]
It seems that if this specific endpoint:
`https://exchange.api.synthetix.io/api/total-locked`
has any issues, whole website stops working.

```
11:56:29:18
   host: [Array]
    }
  },
  response: {
    status: 500,
    statusText: 'Internal Server Error',
    headers: {
      'content-type': 'application/json; charset=utf-8',
      date: 'Wed, 11 Nov 2020 10:56:31 GMT',
      etag: 'W/"22-TIwDtH1wlfpIcIXrl1UGOfMQSTo"',
      server: 'nginx/1.16.1',
      'x-powered-by': 'Express',
      'content-length': '34',
      connection: 'Close'
    },
    config: {
      url: '/total-locked',
      method: 'get',
      headers: [Object],
      baseURL: 'https://exchange.api.synthetix.io/api',
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      adapter: [Function: httpAdapter],
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      validateStatus: [Function: validateStatus],
      data: undefined
    },
    request: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [TLSSocket],
      connection: [TLSSocket],
      _header: 'GET /api/total-locked HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: axios/0.20.0\r\n' +
        'Host: exchange.api.synthetix.io\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      insecureHTTPParser: undefined,
      path: '/api/total-locked',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    data: 'Could not get total locked value'
  },
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
2020-11-11T10:56:31.808Z	daddb553-73d6-48a3-9196-b5453dd070a3	ERROR	Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"Error: Request failed with status code 500","reason":{"message":"Request failed with status code 500","name":"Error","stack":"Error: Request failed with status code 500\n    at createError (/var/task/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/var/task/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/var/task/node_modules/axios/lib/adapters/http.js:244:11)\n    at IncomingMessage.emit (events.js:327:22)\n    at endReadableNT (_stream_readable.js:1220:12)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)","config":{"url":"/total-locked","method":"get","headers":{"Accept":"application/json, text/plain, */*","User-Agent":"axios/0.20.0"},"baseURL":"https://exchange.api.synthetix.io/api","transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1}},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: Error: Request failed with status code 500","    at process.<anonymous> (/var/runtime/index.js:35:15)","    at process.emit (events.js:327:22)","    at processPromiseRejections (internal/process/promises.js:209:33)","    at processTicksAndRejections (internal/process/task_queues.js:98:32)"]}
Unknown application error occurred
```

It should still work, just not show total value locked in this case.

**Comment by clementbalestrat** [comment]
@drptbl Fixed :)
